version: '3.8'

services:
  app:
    container_name: facial_timelapse
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "7860:7860"
    command: [ "python", "app.py" ]
    deploy:
      resources:
        limits:
          memory: "1024M"
